# Generated by Django 4.2.11 on 2024-03-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_dars_app', '0004_alter_card_title_alter_mavzu_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='mavzu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videolar', to='video_dars_app.mavzu'),
        ),
    ]
