# Generated by Django 4.2.11 on 2024-03-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_dars_app', '0005_alter_video_mavzu'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default=1, upload_to='video/image/'),
            preserve_default=False,
        ),
    ]
